# Generated by Django 5.1.2 on 2024-10-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='preprocessing',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='segmentation',
            field=models.CharField(max_length=100),
        ),
    ]
