# Generated by Django 5.1.2 on 2024-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_detectionresult_preprocessing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('preprocessing_technique', models.CharField(choices=[('histogram_equalization', 'Histogram Equalization'), ('clahe', 'CLAHE'), ('gaussian_blur', 'Gaussian Blur'), ('median_filtering', 'Median Filtering'), ('dog', 'Difference of Gaussian'), ('bilateral', 'Bilateral Filtering'), ('no', 'None')], default='no', max_length=50)),
                ('segmentation_technique', models.CharField(choices=[('thresholding', 'Thresholding'), ('otsu_thresholding', 'Otsu Thresholding'), ('kmeans', 'K Means Clustering Segmentation'), ('watershed', 'Watershed Segmentation'), ('color', 'Color Segmentation'), ('grabcut', 'GrabCut Algorithm'), ('no', 'None')], default='no', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='PreprocessingTechnique',
        ),
        migrations.DeleteModel(
            name='SegmentationTechnique',
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
